Merge branch 'android13-5.15-lts' of https://android.googlesource.com/kernel/common into HEAD
* 'android13-5.15-lts' of https://android.googlesource.com/kernel/common:
  Revert "coredump: hand a pidfd to the usermode coredump helper"
  Revert "ipv6: save dontfrag in cork"
  Linux 5.15.185
  perf/arm-cmn: Initialise cmn->cpu earlier
  platform/x86: thinkpad_acpi: Ignore battery threshold change event notification
  platform/x86: fujitsu-laptop: Support Lifebook S2110 hotkeys
  tpm: tis: Double the timeout B to 4s
  nvme-pci: add NVME_QUIRK_NO_DEEPEST_PS quirk for SOLIDIGM P44 Pro
  spi: spi-sun4i: fix early activation
  um: let 'make clean' properly clean underlying SUBARCH as well
  platform/x86: thinkpad_acpi: Support also NEC Lavie X1475JAS
  nfs: don't share pNFS DS connections between net namespaces
  HID: quirks: Add ADATA XPG alpha wireless mouse support
  coredump: hand a pidfd to the usermode coredump helper
  fork: use pidfd_prepare()
  pid: add pidfd_prepare()
  coredump: fix error handling for replace_fd()
  net_sched: hfsc: Address reentrant enqueue adding class to eltree twice
  arm64: dts: qcom: sm8350: Fix typo in pil_camera_mem node
  smb: client: Reset all search buffer pointers when releasing buffer
  smb: client: Fix use-after-free in cifs_fill_dirent
  x86/its: Fix undefined reference to cpu_wants_rethunk_at()
  drm/i915/gvt: fix unterminated-string-initialization warning
  xen/swiotlb: relax alignment requirements
  i3c: master: svc: Fix implicit fallthrough in svc_i3c_master_ibi_work()
  kbuild: Disable -Wdefault-const-init-unsafe
  spi: spi-fsl-dspi: Reset SR flags before sending a new message
  spi: spi-fsl-dspi: Halt the module after a new message transfer
  spi: spi-fsl-dspi: restrict register range for regmap access
  Revert "arm64: dts: allwinner: h6: Use RSB for AXP805 PMIC connection"
  mm/page_alloc.c: avoid infinite retries caused by cpuset race
  memcg: always call cond_resched() after fn()
  Revert "drm/amd: Keep display off while going into S4"
  drm/edid: fixed the bug that hdr metadata was not reset
  platform/x86: dell-wmi-sysman: Avoid buffer overflow in current_password_store()
  llc: fix data loss when reading from a socket in llc_ui_recvmsg()
  ALSA: pcm: Fix race of buffer access at PCM OSS layer
  can: bcm: add missing rcu read protection for procfs content
  can: bcm: add locking for bcm_op runtime updates
  padata: do not leak refcount in reorder_work
  crypto: algif_hash - fix double free in hash_accept
  octeontx2-af: Set LMT_ENA bit for APR table entries
  net/tipc: fix slab-use-after-free Read in tipc_aead_encrypt_done
  sch_hfsc: Fix qlen accounting bug when using peek in hfsc_enqueue()
  net: dwmac-sun8i: Use parsed internal PHY address instead of 1
  bridge: netfilter: Fix forwarding of fragmented packets
  Bluetooth: L2CAP: Fix not checking l2cap_chan security level
  xfrm: Sanitize marks before insert
  remoteproc: qcom_wcnss: Fix on platforms without fallback regulators
  __legitimize_mnt(): check for MNT_SYNC_UMOUNT should be under mount_lock
  xenbus: Allow PVH dom0 a non-local xenstore
  btrfs: correct the order of prelim_ref arguments in btrfs__prelim_ref
  nvmet-tcp: don't restore null sk_state_change
  ALSA: hda/realtek: Add quirk for HP Spectre x360 15-df1xxx
  ASoC: Intel: bytcr_rt5640: Add DMI quirk for Acer Aspire SW3-013
  pinctrl: meson: define the pull up/down resistor value as 60 kOhm
  ASoC: imx-card: Adjust over allocation of memory in imx_card_parse_of()
  drm: Add valid clones check
  drm/atomic: clarify the rules around drm_atomic_state->allow_modeset
  wifi: ath9k: return by of_get_mac_address
  regulator: ad5398: Add device tree support
  spi: zynqmp-gqspi: Always acknowledge interrupts
  wifi: rtw88: Don't use static local variable in rtw8822b_set_tx_power_index_by_rate
  perf/amd/ibs: Fix perf_ibs_op.cnt_mask for CurCnt
  bpftool: Fix readlink usage in get_fd_type
  drm/ast: Find VBIOS mode from regular display size
  HID: usbkbd: Fix the bit shift number for LED_KANA
  scsi: st: Restore some drive settings after reset
  scsi: lpfc: Handle duplicate D_IDs in ndlp search-by D_ID routine
  net/mana: fix warning in the writer of client oob
  rcu: fix header guard for rcu_all_qs()
  rcu: handle quiescent states for PREEMPT_RCU=n, PREEMPT_COUNT=y
  r8169: don't scan PHY addresses > 0
  vxlan: Annotate FDB data races
  media: qcom: camss: csid: Only add TPG v4l2 ctrl if TPG hardware is available
  hwmon: (xgene-hwmon) use appropriate type for the latency value
  clk: qcom: camcc-sm8250: Use clk_rcg2_shared_ops for some RCGs
  wifi: rtw88: Fix download_firmware_validate() for RTL8814AU
  r8152: add vendor/device ID pair for Dell Alienware AW1022z
  ip: fib_rules: Fetch net from fib_rule in fib[46]_rule_configure().
  arch/powerpc/perf: Check the instruction type before creating sample with perf_mem_data_src
  wifi: mac80211: remove misplaced drv_mgd_complete_tx() call
  wifi: mac80211: don't unconditionally call drv_mgd_complete_tx()
  net/mlx5e: reduce rep rxq depth to 256 for ECPF
  net/mlx5e: set the tx_queue_len for pfifo_fast
  net/mlx5: Extend Ethtool loopback selftest to support non-linear SKB
  drm/amd/display: Initial psr_version with correct setting
  drm/amdgpu: reset psp->cmd to NULL after releasing the buffer
  phy: core: don't require set_mode() callback for phy_get_mode() to work
  net/mlx4_core: Avoid impossible mlx4_db_alloc() order value
  media: v4l: Memset argument to 0 before calling get_mbus_config pad op
  smack: recognize ipv4 CIPSO w/o categories
  pinctrl: devicetree: do not goto err when probing hogs in pinctrl_dt_to_map
  ASoC: soc-dai: check return value at snd_soc_dai_set_tdm_slot()
  ASoC: tas2764: Power up/down amp on mute ops
  ASoC: ops: Enforce platform maximum on initial value
  net/mlx5: Apply rate-limiting to high temperature warning
  net/mlx5: Modify LSB bitmask in temperature event to include only the first bit
  ACPI: HED: Always initialize before evged
  PCI: Fix old_size lower bound in calculate_iosize() too
  eth: mlx4: don't try to complete XDP frames in netpoll
  can: c_can: Use of_property_present() to test existence of DT property
  RDMA/core: Fix best page size finding when it can cross SG entries
  EDAC/ie31200: work around false positive build warning
  net: pktgen: fix access outside of user given buffer in pktgen_thread_write()
  wifi: rtw88: Fix rtw_desc_to_mcsrate() to handle MCS16-31
  wifi: rtw88: Fix rtw_init_ht_cap() for RTL8814AU
  wifi: rtw88: Fix rtw_init_vht_cap() for RTL8814AU
  scsi: mpt3sas: Send a diag reset if target reset fails
  clocksource: mips-gic-timer: Enable counter when CPUs start
  MIPS: pm-cps: Use per-CPU variables as per-CPU, not per-core
  MIPS: Use arch specific syscall name match function
  x86/kaslr: Reduce KASLR entropy on most x86 systems
  libbpf: Fix out-of-bound read
  cpuidle: menu: Avoid discarding useful information
  x86/nmi: Add an emergency handler in nmi_desc & use it in nmi_shootdown_cpus()
  drm/amd/display: handle max_downscale_src_width fail check
  x86/build: Fix broken copy command in genimage.sh when making isoimage
  soc: ti: k3-socinfo: Do not use syscon helper to build regmap
  bonding: report duplicate MAC address in all situations
  net: xgene-v2: remove incorrect ACPI_PTR annotation
  drm/amdkfd: KFD release_work possible circular locking
  selftests/net: have `gro.sh -t` return a correct exit code
  net/mlx5: Avoid report two health errors on same syndrome
  firmware: arm_ffa: Set dma_mask for ffa devices
  PCI: brcmstb: Add a softdep to MIP MSI-X driver
  PCI: brcmstb: Expand inbound window size up to 64GB
  fpga: altera-cvp: Increase credit timeout
  drm/mediatek: mtk_dpi: Add checks for reg_h_fre_con existence
  ARM: at91: pm: fix at91_suspend_finish for ZQ calibration
  hwmon: (gpio-fan) Add missing mutex locks
  x86/bugs: Make spectre user default depend on MITIGATION_SPECTRE_V2
  clk: imx8mp: inform CCF of maximum frequency of clocks
  media: uvcvideo: Add sanity check to uvc_ioctl_xu_ctrl_map
  ipv4: fib: Move fib_valid_key_len() to rtm_to_fib_config().
  net: pktgen: fix mpls maximum labels list parsing
  net: ethernet: ti: cpsw_new: populate netdev of_node
  pinctrl: bcm281xx: Use "unsigned int" instead of bare "unsigned"
  media: cx231xx: set device_caps for 417
  drm/amdgpu: Do not program AGP BAR regs under SRIOV in gfxhub_v1_0.c
  remoteproc: qcom_wcnss: Handle platforms with only single power domain
  orangefs: Do not truncate file size
  dm cache: prevent BUG_ON by blocking retries on failed device resumes
  media: c8sectpfe: Call of_node_put(i2c_bus) only once in c8sectpfe_probe()
  ARM: tegra: Switch DSI-B clock parent to PLLD on Tegra114
  ieee802154: ca8210: Use proper setters and getters for bitwise types
  rtc: ds1307: stop disabling alarms on probe
  tcp: bring back NUMA dispersion in inet_ehash_locks_alloc()
  powerpc/prom_init: Fixup missing #size-cells on PowerBook6,7
  arm64: tegra: p2597: Fix gpio for vdd-1v8-dis regulator
  crypto: lzo - Fix compression buffer overrun
  cpufreq: tegra186: Share policy per cluster
  ASoC: qcom: sm8250: explicitly set format in sm8250_be_hw_params_fixup()
  auxdisplay: charlcd: Partially revert "Move hwidth and bwidth to struct hd44780_common"
  ipv6: save dontfrag in cork
  mmc: sdhci: Disable SD card clock before changing parameters
  arm64/mm: Check PUD_TYPE_TABLE in pud_bad()
  netfilter: conntrack: Bound nf_conntrack sysctl writes
  timer_list: Don't use %pK through printk()
  posix-timers: Add cond_resched() to posix_timer_add() search loop
  RDMA/uverbs: Propagate errors from rdma_lookup_get_uobject()
  xen: Add support for XenServer 6.1 platform device
  dm: restrict dm device size to 2^63-512 bytes
  crypto: octeontx2 - suppress auth failure screaming due to negative tests
  kbuild: fix argument parsing in scripts/config
  ASoC: mediatek: mt6359: Add stub for mt6359_accdet_enable_jack_detect
  rtc: rv3032: fix EERD location
  tcp: reorganize tcp_in_ack_event() and tcp_count_delivered()
  vfio/pci: Handle INTx IRQ_NOTCONNECTED
  scsi: st: ERASE does not change tape location
  scsi: st: Tighten the page format heuristics with MODE SELECT
  ext4: reorder capability check last
  um: Update min_low_pfn to match changes in uml_reserved
  um: Store full CSGSFS and SS register from mcontext
  dlm: make tcp still work in multi-link env
  i3c: master: svc: Fix missing STOP for master request
  btrfs: send: return -ENAMETOOLONG when attempting a path that is too long
  btrfs: get zone unusable bytes while holding lock at btrfs_reclaim_bgs_work()
  btrfs: avoid linker error in btrfs_find_create_tree_block()
  btrfs: make btrfs_discard_workfn() block_group ref explicit
  i2c: pxa: fix call balance of i2c->clk handling routines
  i2c: qup: Vote for interconnect bandwidth to DRAM
  wifi: mt76: only mark tx-status-failed frames as ACKed on mt76x0/2
  mmc: host: Wait for Vdd to settle on card power off
  libnvdimm/labels: Fix divide error in nd_label_data_init()
  PCI: vmd: Disable MSI remapping bypass under Xen
  pNFS/flexfiles: Report ENETDOWN as a connection error
  tools/build: Don't pass test log files to linker
  PCI: dwc: ep: Ensure proper iteration over outbound map windows
  lockdep: Fix wait context check on softirq for PREEMPT_RT
  dql: Fix dql->limit value when reset.
  thermal/drivers/qoriq: Power down TMU on system suspend
  SUNRPC: rpcbind should never reset the port to the value '0'
  SUNRPC: rpc_clnt_set_transport() must not change the autobind setting
  NFSv4: Treat ENETUNREACH errors as fatal for state recovery
  fbdev: core: tileblit: Implement missing margin clearing for tileblit
  fbcon: Use correct erase colour for clearing in fbcon
  fbdev: fsl-diu-fb: add missing device_remove_file()
  mailbox: use error ret code of of_parse_phandle_with_args()
  tracing: Mark binary printing functions with __printf() attribute
  NFSv4: Check for delegation validity in nfs_start_delegation_return_locked()
  kconfig: merge_config: use an empty file as initfile
  samples/bpf: Fix compilation failure for samples/bpf on LoongArch Fedora
  bpf: fix possible endless loop in BPF map iteration
  net: enetc: refactor bulk flipping of RX buffers to separate function
  cgroup: Fix compilation issue due to cgroup_mutex not being exported
  dma-mapping: avoid potential unused data compilation warning
  virtio_ring: Fix data race by tagging event_triggered as racy for KCSAN
  scsi: target: iscsi: Fix timeout on deleted connection
  ANDROID: binder: fix minimum node priority comparison
  UPSTREAM: PCI/ASPM: Fix L1SS saving
  UPSTREAM: PCI/ASPM: Save parent L1SS config in pci_save_aspm_l1ss_state()
  ANDROID: 16K: Remove ELF padding entry from map_file ranges
  ANDROID: ABI: Add to QCOM symbols list
  UPSTREAM: binder: fix potential UAF of target_{proc,thread}

Change-Id: I1ed8e126de6f5d19a7a9f095c4736201c3880e8b